// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleApp.DAL.EntityFramework.Context;

#nullable disable

namespace VehicleApp.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221116112409_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleApp.Core.Entities.Concrete.Boat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Boats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Duffy Boats",
                            Color = "White",
                            CreationDate = new DateTime(2022, 11, 16, 14, 24, 9, 542, DateTimeKind.Local).AddTicks(2878),
                            Model = "SUN CRUISER 22",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Duffy Boats",
                            Color = "Blue",
                            CreationDate = new DateTime(2022, 11, 16, 14, 24, 9, 542, DateTimeKind.Local).AddTicks(2881),
                            Model = "SUN CRUISER 22",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Duffy Boats",
                            Color = "Black",
                            CreationDate = new DateTime(2022, 11, 16, 14, 24, 9, 542, DateTimeKind.Local).AddTicks(2884),
                            Model = "SUN CRUISER 22",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Duffy Boats",
                            Color = "Red",
                            CreationDate = new DateTime(2022, 11, 16, 14, 24, 9, 542, DateTimeKind.Local).AddTicks(2886),
                            Model = "BAY ISLAND 22",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Duffy Boats",
                            Color = "White",
                            CreationDate = new DateTime(2022, 11, 16, 14, 24, 9, 542, DateTimeKind.Local).AddTicks(2888),
                            Model = "BAY ISLAND 22",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Duffy Boats",
                            Color = "Blue",
                            CreationDate = new DateTime(2022, 11, 16, 14, 24, 9, 542, DateTimeKind.Local).AddTicks(2890),
                            Model = "BAY ISLAND 22",
                            Status = 1
                        });
                });

            modelBuilder.Entity("VehicleApp.Core.Entities.Concrete.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Busses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Karsan",
                            Color = "Red",
                            CreationDate = new DateTime(2022, 11, 16, 14, 24, 9, 542, DateTimeKind.Local).AddTicks(2866),
                            Model = "e-ATAK",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Karsan",
                            Color = "Blue",
                            CreationDate = new DateTime(2022, 11, 16, 14, 24, 9, 542, DateTimeKind.Local).AddTicks(2869),
                            Model = "e-ATAK",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Karsan",
                            Color = "White",
                            CreationDate = new DateTime(2022, 11, 16, 14, 24, 9, 542, DateTimeKind.Local).AddTicks(2871),
                            Model = "e-ATAK",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Karsan",
                            Color = "Black",
                            CreationDate = new DateTime(2022, 11, 16, 14, 24, 9, 542, DateTimeKind.Local).AddTicks(2872),
                            Model = "e-ATA 10",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Karsan",
                            Color = "White",
                            CreationDate = new DateTime(2022, 11, 16, 14, 24, 9, 542, DateTimeKind.Local).AddTicks(2874),
                            Model = "e-ATA 10",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Karsan",
                            Color = "Blue",
                            CreationDate = new DateTime(2022, 11, 16, 14, 24, 9, 542, DateTimeKind.Local).AddTicks(2876),
                            Model = "e-ATA 10",
                            Status = 1
                        });
                });

            modelBuilder.Entity("VehicleApp.Core.Entities.Concrete.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Headlights")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Wheels")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Tesla",
                            Color = "Red",
                            CreationDate = new DateTime(2022, 11, 16, 14, 24, 9, 542, DateTimeKind.Local).AddTicks(2834),
                            Headlights = false,
                            Model = "S",
                            Status = 1,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Tesla",
                            Color = "Black",
                            CreationDate = new DateTime(2022, 11, 16, 14, 24, 9, 542, DateTimeKind.Local).AddTicks(2852),
                            Headlights = false,
                            Model = "S",
                            Status = 1,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Tesla",
                            Color = "Blue",
                            CreationDate = new DateTime(2022, 11, 16, 14, 24, 9, 542, DateTimeKind.Local).AddTicks(2855),
                            Headlights = false,
                            Model = "S",
                            Status = 1,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Togg",
                            Color = "Red",
                            CreationDate = new DateTime(2022, 11, 16, 14, 24, 9, 542, DateTimeKind.Local).AddTicks(2856),
                            Headlights = false,
                            Model = "C-SUV",
                            Status = 1,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Togg",
                            Color = "White",
                            CreationDate = new DateTime(2022, 11, 16, 14, 24, 9, 542, DateTimeKind.Local).AddTicks(2858),
                            Headlights = false,
                            Model = "C-SUV",
                            Status = 1,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Togg",
                            Color = "Blue",
                            CreationDate = new DateTime(2022, 11, 16, 14, 24, 9, 542, DateTimeKind.Local).AddTicks(2861),
                            Headlights = false,
                            Model = "C-SUV",
                            Status = 1,
                            Wheels = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
